name: Install and Run Inkcollector for Lorcast

on:
  # Trigger the workflow manually from the GitHub UI
  workflow_dispatch:

  # Trigger the workflow every Wednesday at midnight (UTC)
  # schedule:
    # - cron: '0 0 * * 3'  # 0 0 * * 3 represents 12:00 AM UTC on Wednesday

jobs:
  run_inkcollector:
    runs-on: ubuntu-latest  # You can use different OS like macOS or Windows here if needed
    permissions:
      contents: write
      
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change to the version you need
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install inkcollector
          inkcollector --version

      # Step 4: Run inkcollector
      - name: Run Inkcollector
        run: |
          inkcollector lorcast all --outputformat JSON

      # Step 5: Create a new folder with today's date and move the contents of lorcast
      - name: Move lorcast contents to a date-stamped folder
        run: |
          # Get today's date in YYYY-MM-DD format
          DATE=$(date +'%Y-%m-%d')

          # Check if 'data/lorcast' directory exists
          if [ -d "data/lorcast" ]; then
            # Create 'data/raw/lorcast' folder if it doesn't exist
            mkdir -p "data/raw/lorcast"
            
            # Create a date-stamped folder inside 'data/raw/lorcast'
            mkdir -p "data/raw/lorcast/$DATE"
            
            # Move all contents of 'lorcast' to the new date-stamped folder
            mv lorcast/* "data/raw/lorcast/$DATE/"
            
            echo "Moved contents of lorcast to data/raw/$DATE/"
          else
            echo "lorcast folder not found!"
          fi
          
      # Step 6: Make changes and commit them
      - name: Make changes and commit
        run: |          
          # Set up Git with the GitHub Actions bot user
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the change and commit it
          git add .
          git commit -m "Collected data from lorcast on $(date)"

      # Step 7: Push the changes back to the repository
      - name: Push changes to repository
        run: |
          git push https://github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
