name: Lorcana Data Extraction

on:
  schedule:
    # Run on the 1st day of every month at 2 AM UTC
    - cron: '0 2 1 * *'
  workflow_dispatch:
    # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'scripts/lorcana_data_extractor.py'
      - '.github/workflows/lorcast-extraction.yml'

permissions:
  contents: write

jobs:
  extract-lorcana-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install inkcollector==1.0.0
        
    - name: Run Lorcana data extraction
      run: |
        python scripts/lorcana_data_extractor.py
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Update Lorcana data - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
