name: Processing Lorcast Data

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Data Loading Workflow"]
    types:
      - completed

jobs:
  post_process:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change to the version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd scripts/lorcast_data_loader
          if [ -f scripts/lorcast_data_loader/requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run Processing Script
      - name: Run processing script
        run: |
          echo "Running processing script..."
          python -m main.py
          
