name: Processing Raw Data

on:
  # Trigger the workflow manually from the GitHub UI
  workflow_dispatch:

  # Trigger the workflow every Monday at midnight (UTC)
  schedule:
    - cron: '0 0 * * 1'  # 0 0 * * 1 represents 12:00 AM UTC on Monday

jobs:
  run_lorcast:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run lorcast.py
        run: python3 scripts/lorcast.py

      - name: Make changes and commit
        run: |
          # Set up Git with the GitHub Actions bot user
          git config --local user.name "GitHub Actions"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if their any changes to commit
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

          # Add the change and commit it
          git add .
          git commit -m "Processed data from lorcast on $(date)"

      - name: Push changes to repository
        run: |
          git push https://github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
